# Generated by Django 5.0.6 on 2024-05-25 07:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='nikas/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('SW', 'SWIMMING'), ('CR', 'CRICKET'), ('PT', 'URDU POETRY'), ('MV', 'MOVIES')], default='PT', max_length=2)),
            ],
        ),
    ]
