# Generated by Django 5.0.6 on 2024-08-18 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nika', '0006_alter_projects_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='url',
            new_name='live_url',
        ),
    ]
